name: Tugas Negara

on: 
  schedule:
    - cron: 6 6 * * *

jobs:
  ngapain_nih:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          chmod +x .github/tools/tugas_negara
          .github/tools/tugas_negara
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_API_URL: "https://api.github.com/user"
