name: Tugas Negara

on: 
  schedule:
    - cron: 6 6 * * *

jobs:
  ngapain_nih:
    runs-on: ubuntu-latest
    steps:
      - run: ${PWD}/.github/tools/tugas_negara
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_API_URL: "https://api.github.com/user"
